<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title><?= $this->escape($this->title ?: "Grey Mist") ?></title>
        <link rel="icon" type="image/x-icon" href="/_greymist/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <link href="/_greymist/vendor/fontawesome/css/all.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="/_greymist/vendor/fonts/fonts.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/_greymist/css/bootstrap.css" rel="stylesheet" />
        <link href="/_greymist/css/grey-mist.css" rel="stylesheet" />
    <?= $this->pageHead ?? "" ?>

    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top">Grey Mist</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#projects">Projects</a></li>
                        <li class="nav-item"><a class="nav-link" href="#signup">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <?= $this->layout()->content ?>
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Copyright &copy; WebTigers 2026</div></footer>
        <!-- Bootstrap core JS-->
        <script src="/_greymist/js/bootstrap.bundle.js"></script>
        <!-- Core theme JS-->
        <script src="/_greymist/js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at #